package credit.suisse.service;

import credit.suisse.db.DatabaseConnection;
import credit.suisse.db.HsqlDatabaseConnection;
import credit.suisse.pojo.EventConstants;
import credit.suisse.pojo.EventResult;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.List;
import java.util.logging.Logger;

/**
 * @author adheli.tavares
 */
public class EventServiceImpl implements EventService {

    private DatabaseConnection dbConnection;
    private static final Logger logger = Logger.getGlobal();
    
    public EventServiceImpl() {
        this.dbConnection = new HsqlDatabaseConnection();
    }
    
    public void createTable() {
        try {
            String sql = "CREATE TABLE EVENT(" +
                    "ID_PK INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, " +
                    "ID VARCHAR(250) NOT NULL, " +
                    "DURATION SMALLINT NOT NULL, " +
                    "TYPE VARCHAR(250), " +
                    "HOST VARCHAR(250), " +
                    "ALERT BOOLEAN NOT NULL)";

            dbConnection.getConnection().prepareStatement(sql).executeUpdate();

            logger.info("Event table created successfully!");
        } catch (SQLException sqlExcept) {
            logger.severe(String.format("Couldn't create Event table!\n%s", sqlExcept.getMessage()));
        } finally {
            dbConnection.closeConnection();
		}
    }

    public void cleanTable() {
        try {
            String sql = "DELETE FROM EVENT";

            dbConnection.getConnection().prepareStatement(sql).executeUpdate();
            logger.info("All data from table Event was erased!");
        } catch (SQLException sqlExcept) {
            logger.severe(String.format("Couldn't delete data from Event table!\n%s", sqlExcept.getMessage()));
        } finally {
            dbConnection.closeConnection();
		}
    }

    public void saveEventResult(EventResult result) {
        try {
            String sql = "INSERT INTO EVENT(ID, DURATION, TYPE, HOST, ALERT) VALUES (?,?,?,?,?)";
            PreparedStatement stmt = dbConnection.getConnection().prepareStatement(sql);
            stmt.setString(EventConstants.ID.getIndex(), result.getId());
            stmt.setInt(EventConstants.DURATION.getIndex(), result.getDuration());
            stmt.setString(EventConstants.TYPE.getIndex(), result.getType());
            stmt.setString(EventConstants.HOST.getIndex(), result.getHost());
            stmt.setBoolean(EventConstants.ALERT.getIndex(), result.getAlert());

            stmt.execute();
            stmt.close();

            logger.info(String.format("Event %s saved!", result.getId()));
        } catch (SQLException sqlExcept) {
            logger.severe(String.format("Couldn't insert event %s!\n%s", result.getId(), sqlExcept.getMessage()));
        } finally {
            dbConnection.closeConnection();
		}
    }

    public List<EventResult> listAllEvents() {
        List<EventResult> results = new ArrayList<>();
        try {
            logger.info("Selecting all items from Event.");

            String sql = "SELECT * FROM EVENT";
            ResultSet resultSet = dbConnection.getConnection().prepareStatement(sql).executeQuery();

            while (resultSet.next()) {
                EventResult result = new EventResult(resultSet.getString(EventConstants.ID.getValue()),
                        resultSet.getInt(EventConstants.DURATION.getValue()),
                        resultSet.getBoolean(EventConstants.ALERT.getValue()));
                result.setType(resultSet.getString(EventConstants.TYPE.getValue()));
                result.setHost(resultSet.getString(EventConstants.HOST.getValue()));

                results.add(result);
            }
        } catch (SQLException sqlExcept) {
            logger.severe(String.format("Couldn't read values from table Event.\n%s", sqlExcept.getMessage()));
        } finally {
        	dbConnection.closeConnection();
		}

        return results;
    }
}
